Rework wishlist into a proper table
YunoHost/doc pull request #1395
Opened 2020-09-09 20:42 UTC by alexAubin

- Rework wishlist to have the various info (name, descr, website, upstream/code, package draft) in a table
- Integrate inprogress/notworking apps
- Switch every link to https
- Remove links that do not properly respond on https
- Arbitrarily remove a few apps that are not relevant / not maintained anymore / wtf / ...

Note that I realized that (I think) some apps that have a package draft have a non-free license ... that goes back to the stupidly old debate about free vs. non-free apps in the catalog ... but these are currently listed in apps.json. So if we want to be consistent with the "no not-free apps allowed" we should also remove them from apps.json ...

2020-09-09 21:02 UTC, ericgaspar commented
It's much more readable! good work🏋

2020-09-10 07:53 UTC, ericgaspar requested changes
Quick look. Added request #1315

2020-09-10 07:53 UTC, ericgaspar commented on apps_wishlist.md
> +| [Invoice Ninja](https://www.invoiceninja.com) |  | [Upstream](https://github.com/invoiceninja/invoiceninja) |  |
```suggestion

```
We can remove InvoiceNinja out of the list as it is up and running https://github.com/YunoHost-Apps/invoiceninja_ynh

2020-09-10 07:53 UTC, ericgaspar commented on apps_wishlist.md
> +| mumble_admin_plugin | Mumble-server web interface |  | [Package Draft](https://github.com/matlink/mumble_admin_plugin_ynh) |
```suggestion
| mumble_admin_plugin | Mumble-server web interface |  | [Package Draft](https://github.com/matlink/mumble_admin_plugin_ynh) |
| Mumble-web  |  Mumble web interface |  [Upstream](https://github.com/Johni0702/mumble-web) | [Package Draft](https://github.com/YunoHost-Apps/mumbleserver_ynh/pull/32) | 
```
Add Mumble Web from request #1315

2020-09-10 11:51 UTC, ericgaspar commented on apps_wishlist.md
> +| [rocketchat](https://rocket.chat) | the ultimate chat platform |  | [Package Draft](https://github.com/YunoHost-Apps/rocketchat_ynh) |
I guess we can also close this request #1291

2020-09-10 12:28 UTC, ericgaspar reviewed
I closed the request #1291 because it is now part of Package Draft list

2020-09-11 03:05 UTC, comradekingu commented on apps_wishlist.md
> +| [duniter](https://duniter.org) | Participate to the duniter blockchain |  | [Package Draft](https://github.com/YunoHost-Apps/duniter_ynh) |
```suggestion
| [duniter](https://duniter.org) | Participate to the Duniter blockchain |  | [Package Draft](https://github.com/YunoHost-Apps/duniter_ynh) |
```
As per https://duniter.org/en/introduction/

2020-09-11 03:05 UTC, comradekingu commented on apps_wishlist.md
> +| [duniter](https://duniter.org) | Participate to the duniter blockchain |  | [Package Draft](https://github.com/YunoHost-Apps/duniter_ynh) |
```suggestion
| [duniter](https://duniter.org) | Participate in the Duniter blockchain |  | [Package Draft](https://github.com/YunoHost-Apps/duniter_ynh) |
```
As per https://duniter.org/en/introduction/

2020-09-11 03:07 UTC, comradekingu commented on apps_wishlist.md
> +| dynette | Dynette is a dyndns server | [Upstream](https://github.com/YunoHost/dynette) | [Package Draft](https://github.com/YunoHost-Apps/dynette_ynh) |
```suggestion
| dynette | Dynette is a DDNS server | [Upstream](https://github.com/YunoHost/dynette) | [Package Draft](https://github.com/YunoHost-Apps/dynette_ynh) |
```
As per https://en.wikipedia.org/wiki/Dynamic_DNS

2020-09-11 03:10 UTC, comradekingu commented on apps_wishlist.md
> +| [Kiwix](https://www.kiwix.org/) | Offline wikipedia | [Upstream](https://github.com/kiwix/) |  |
```suggestion
| [Kiwix](https://www.kiwix.org/) | Offline Wikipedia or other sites | [Upstream](https://github.com/kiwix/) |  |
```
As per https://www.kiwix.org/en/

2020-09-11 03:10 UTC, comradekingu commented on apps_wishlist.md
> +| [Lemmy](https://dev.lemmy.ml) | A federated alternative to reddit | [Upstream](https://github.com/dessalines/lemmy) |  |
```suggestion
| [Lemmy](https://dev.lemmy.ml) | A federated alternative to Reddit | [Upstream](https://github.com/dessalines/lemmy) |  |
```

2020-09-11 03:12 UTC, comradekingu commented on apps_wishlist.md
> +| [mailman3](https://docs.mailman3.org/) | Electronic mailing lists manager |  | [Package Draft](https://github.com/YunoHost-Apps/mailman3_ynh) |
```suggestion
| [mailman3](https://docs.mailman3.org/) | Electronic mailing list manager |  | [Package Draft](https://github.com/YunoHost-Apps/mailman3_ynh) |
```
As per the URL

2020-09-11 03:13 UTC, comradekingu commented on apps_wishlist.md
> +| [mopidy](https://www.mopidy.com/) | An extensible music server |  | [Package Draft](https://github.com/YunoHost-Apps/mopidy_ynh) |
Is "extensible" correct?

2020-09-11 03:15 UTC, comradekingu commented on apps_wishlist.md
> +| nexusoss | sonatype nexus repository manager OSS |  | [Package Draft](https://github.com/YunoHost-Apps/nexusoss_ynh) |
```suggestion
| nexusoss | Sonatype Nexus Repository manager OSS |  | [Package Draft](https://github.com/YunoHost-Apps/nexusoss_ynh) |
```
As per https://www.sonatype.com/nexus/repository-pro

2020-09-11 03:16 UTC, comradekingu commented on apps_wishlist.md
> +| [osjs](https://www.os-js.org/) | Desktop you have accesss through your browser |  | [Package Draft](https://github.com/YunoHost-Apps/osjs_ynh) |
```suggestion
| [osjs](https://www.os-js.org/) | Desktop you have access to through your web-browser |  | [Package Draft](https://github.com/YunoHost-Apps/osjs_ynh) |
```

2020-09-11 03:17 UTC, comradekingu commented on apps_wishlist.md
> +| [pagure](https://pagure.io/pagure) | A git forge |  | [Package Draft](https://github.com/YunoHost-Apps/pagure_ynh) |
```suggestion
| [pagure](https://pagure.io/pagure) | A Git forge |  | [Package Draft](https://github.com/YunoHost-Apps/pagure_ynh) |
```

2020-09-11 03:17 UTC, comradekingu commented on apps_wishlist.md
> +| [Passbolt](https://www.passbolt.com) | Passwords manager | [Upstream](https://github.com/passbolt) |  |
```suggestion
| [Passbolt](https://www.passbolt.com) | Password manager | [Upstream](https://github.com/passbolt) |  |
```

2020-09-11 03:18 UTC, comradekingu commented on apps_wishlist.md
> +| [plonecms](plone.org) | Create a modern Website with a CMS written in python |  | [Package Draft](https://github.com/YunoHost-Apps/plonecms_ynh) |
```suggestion
| [plonecms](plone.org) | Create a modern website with a CMS written in Python |  | [Package Draft](https://github.com/YunoHost-Apps/plonecms_ynh) |
```

2020-09-11 03:18 UTC, comradekingu commented on apps_wishlist.md
> +| [prestashop](https://www.prestashop.com/) | Create a E-commerce Website |  | [Package Draft](https://github.com/YunoHost-Apps/prestashop_ynh) |
```suggestion
| [prestashop](https://www.prestashop.com/) | Create an e-commerce website |  | [Package Draft](https://github.com/YunoHost-Apps/prestashop_ynh) |
```

2020-09-11 03:19 UTC, comradekingu commented on apps_wishlist.md
> +| [psitransfer](https://psi.cx/tags/PsiTransfer/) | Transfer files or images without problem |  | [Package Draft](https://github.com/YunoHost-Apps/psitransfer_ynh) |
```suggestion
| [psitransfer](https://psi.cx/tags/PsiTransfer/) | Transfer files or images without problems |  | [Package Draft](https://github.com/YunoHost-Apps/psitransfer_ynh) |
```

2020-09-11 03:20 UTC, comradekingu commented on apps_wishlist.md
> +| RemoteStorage | A remoteStorage server implementation written in PHP | [Upstream](https://github.com/fkooman/php-remote-storage) | [Package Draft](https://github.com/YunoHost-Apps/RemoteStorage_ynh
```suggestion
| remoteStorage | A remoteStorage server implementation written in PHP | [Upstream](https://github.com/fkooman/php-remote-storage) | [Package Draft](https://github.com/YunoHost-Apps/RemoteStorage_ynh) |
```

2020-09-11 03:20 UTC, comradekingu commented on apps_wishlist.md
> +| [roadiz](https://www.roadiz.io) | Create a modern Website |  | [Package Draft](https://github.com/YunoHost-Apps/roadiz_ynh) |
```suggestion
| [roadiz](https://www.roadiz.io) | Create a modern website |  | [Package Draft](https://github.com/YunoHost-Apps/roadiz_ynh) |
```

2020-09-11 03:21 UTC, comradekingu commented on apps_wishlist.md
> +| [rocketchat](https://rocket.chat) | the ultimate chat platform |  | [Package Draft](https://github.com/YunoHost-Apps/rocketchat_ynh) |
```suggestion
| [rocketchat](https://rocket.chat) | A chat platform |  | [Package Draft](https://github.com/YunoHost-Apps/rocketchat_ynh) |
```

2020-09-11 03:22 UTC, comradekingu commented on apps_wishlist.md
> +| [rspamdui](https://rspamd.com/webui) | An web UI for rspamd spam filtering system |  | [Package Draft](https://github.com/YunoHost-Apps/rspamdui_ynh) |
```suggestion
| [rspamdui](https://rspamd.com/webui) | A web UI for the Rspamd spam filtering system |  | [Package Draft](https://github.com/YunoHost-Apps/rspamdui_ynh) |
```
As per https://rspamd.com/

2020-09-11 03:22 UTC, comradekingu commented on apps_wishlist.md
> +| [Schleuder](https://schleuder.org/schleuder/docs/concept.html) | A gpg-enabled mailing list manager |  |  |
```suggestion
| [Schleuder](https://schleuder.org/schleuder/docs/concept.html) | A GPG-enabled mailing list manager |  |  |
```

2020-09-11 03:23 UTC, comradekingu commented on apps_wishlist.md
> +| [shadowsocks](https://shadowsocks.org) | A socks5 proxy to protect your Internet trafic |  | [Package Draft](https://github.com/YunoHost-Apps/shadowsocks_ynh) |
```suggestion
| [shadowsocks](https://shadowsocks.org) | A SOCKS5 proxy to protect your Internet traffic |  | [Package Draft](https://github.com/YunoHost-Apps/shadowsocks_ynh) |
```

2020-09-11 03:25 UTC, comradekingu commented on apps_wishlist.md
> +| transwhat | A getway to whatsapp from Jabber |  | [Package Draft](https://github.com/Josue-T/transwhat_ynh) |
```suggestion
| transwhat | A gateway to WhatsApp from Jabber |  | [Package Draft](https://github.com/Josue-T/transwhat_ynh) |
```
As per https://no.wikipedia.org/wiki/WhatsApp

2020-09-11 03:25 UTC, comradekingu commented on apps_wishlist.md
> +| tutao | End-To-End Encrypted Mail Client | [Upstream](https://github.com/tutao/tutanota/) | [Package Draft](https://github.com/YunoHost-Apps/tutao_ynh) |
```suggestion
| tutao | End-to-end encrypted e-mail client | [Upstream](https://github.com/tutao/tutanota/) | [Package Draft](https://github.com/YunoHost-Apps/tutao_ynh) |
```

2020-09-11 03:26 UTC, comradekingu commented on apps_wishlist.md
> +| [TwitRSS.me](https://twitrss.me/) | Create RSS feeds from twitter | [Upstream](https://github.com/ciderpunx/twitrssme) |  |
```suggestion
| [TwitRSS.me](https://twitrss.me/) | Create RSS feeds from Twitter | [Upstream](https://github.com/ciderpunx/twitrssme) |  |
```

2020-09-11 03:26 UTC, comradekingu commented on apps_wishlist.md
> +| [yellowcms](https://datenstrom.se/yellow/) | CMS for simple website |  | [Package Draft](https://github.com/YunoHost-Apps/yellowcms_ynh) |
```suggestion
| [yellowcms](https://datenstrom.se/yellow/) | CMS for simple websites |  | [Package Draft](https://github.com/YunoHost-Apps/yellowcms_ynh) |
```

2020-09-11 03:27 UTC, comradekingu commented on apps_wishlist.md
> +| [yunohost](https://yunohost.org) | Yunohost in Yunohost, crazy :D ! |  | [Package Draft](https://github.com/aymhce/yunohost_ynh) |
```suggestion
| [yunohost](https://yunohost.org) | YunoHost in YunoHost, crazy :D ! |  | [Package Draft](https://github.com/aymhce/yunohost_ynh) |
```

2020-09-11 03:28 UTC, comradekingu commented on apps_wishlist.md
> +<div class="alert alert-info">Before adding an app in this wishlist, please check your app is not <a href="/apps">already available in Yunohost's app catalog</a></div>
```suggestion
<div class="alert alert-info">Before adding an app in this wish-list, please check your app is not <a href="/apps">already available in YunoHost's app catalogue</a></div>
```

2020-09-11 03:28 UTC, comradekingu commented on apps_wishlist.md
> +| [abantecart](https://abantecart.com) | Create a E-commerce Website |  | [Package Draft](https://github.com/YunoHost-Apps/abantecart_ynh) |
```suggestion
| [abantecart](https://abantecart.com) | Create an e-commerce website |  | [Package Draft](https://github.com/YunoHost-Apps/abantecart_ynh) |
```

2020-09-11 03:31 UTC, comradekingu commented on apps_wishlist.md
> +| adhocserver | An adhoc Server for the sony PSP |  | [Package Draft](https://github.com/matlink/adhocserver_ynh) |
```suggestion
| adhocserver | An ad hoc server for the Sony PSP |  | [Package Draft](https://github.com/matlink/adhocserver_ynh) |
```
Not 100% sure this isn't the "adhoc party", but as per https://manuals.playstation.net/document/en/psp/current/settings/adhoc.html

2020-09-11 03:32 UTC, comradekingu commented on apps_wishlist.md
> +| [askbot](https://askbot.com/) | Questions & Answers |  | [Package Draft](https://github.com/zamentur/askbot_ynh) |
```suggestion
| [askbot](https://askbot.com/) | Questions and answers |  | [Package Draft](https://github.com/zamentur/askbot_ynh) |
```

2020-09-11 03:33 UTC, comradekingu commented on apps_wishlist.md
> +| [democracyos](https://democracyos.org/) | Vote / take decision in a collective |  | [Package Draft](https://github.com/YunoHost-Apps/democracyos_ynh) |
```suggestion
| [democracyos](https://democracyos.org/) | Vote / make decisions in a collective |  | [Package Draft](https://github.com/YunoHost-Apps/democracyos_ynh) |
```

2020-09-11 03:34 UTC, comradekingu commented on apps_wishlist.md
> +| [ftssolr](https://wiki.dovecot.org/Plugins/FTS/Solr) | Full Text Search via IMAP through a Solr indexing server |  | [Package Draft](https://github.com/YunoHost-Apps/ftssolr_ynh) |
```suggestion
| [ftssolr](https://wiki.dovecot.org/Plugins/FTS/Solr) | Full-text search via IMAP through a Solr indexing server |  | [Package Draft](https://github.com/YunoHost-Apps/ftssolr_ynh) |
```

2020-09-11 03:35 UTC, comradekingu commented on apps_wishlist.md
> +| galette | Membership management for non profit organizations |  | [Package Draft](https://github.com/YunoHost-Apps/galette_ynh) |
```suggestion
| galette | Membership management for non-profit organizations |  | [Package Draft](https://github.com/YunoHost-Apps/galette_ynh) |
```

2020-09-11 03:36 UTC, comradekingu commented on apps_wishlist.md
> +| gogs_webhost | Turn a gogs repository to static web hosting |  | [Package Draft](https://github.com/YunoHost-Apps/gogs_webhost_ynh) |
```suggestion
| gogs_webhost | Turn a Gogs repository to static web hosting |  | [Package Draft](https://github.com/YunoHost-Apps/gogs_webhost_ynh) |
```
As per https://manuals.playstation.net/document/en/psp/current/settings/adhoc.html

2020-09-11 11:36 UTC, merged