yunohost ne permet plus d’autoriser ssh
YunoHost/doc pull request #1716
Opened 2021-07-10 16:34 UTC by ttamttam

Mais on peut passer par le panneau d’administration

2021-07-11 18:05 UTC, tituspijean requested changes
Bonjour, et merci pour cette première contribution!

Deux points:
- Malgré leur inexactitude typographique, il me semble que nous préférons utiliser les apostrophes dactylographiques `'` dans le code. J'imagine qu'elles sont plus facilement accessibles sur les claviers. Par contre, on peut tout à fait se pencher sur la question, et pourquoi pas les transformer automatiquement en apostrophes typographiques `’` au niveau du CMS qui se charge d'afficher la documentation, ou alors mettre en place un robot qui fait les modifs pour nous? Je laisse d'autres membres de l'équipe intervenir à ce sujet, on a rien de défini il me semble.
- Ta PR par d'un mauvais présupposé (on ne pourrait plus définir les autorisations SSH via la ligne de commande). En fait c'est devenu une permission à part entière, et il faut passer par la commande `yunohost user permission add ssh.main <user>`

Je t'invite à amender ta *pull request* en remettant les apostrophes droites et en corrigeant plutôt la commande. 😉

2021-07-11 18:42 UTC, ericgaspar requested changes
Ça me rappelle mes toutes premières PR ou je faisais la même chose (il ne reste d’ailleurs rien de ce travail, tout ayant été remplacé en apostrophes droites :). D’un point de vue typographique c’est évidemment mieux d’intégrer de vraies apostrophes, mais comme dit Titus les apostrophes droites semblent être le choix par défaut dans les éditeurs de code.
Par contre on peut peut-être faire un effort pour les titres qui eux sont disgracieux avec ces apostrophes droites.

2021-07-11 18:42 UTC, ericgaspar commented on pages/01.administrate/06.overview/04.commandline/ssh.fr.md
>  ## La ligne de commande Yunohost
```suggestion
## La ligne de commande YunoHost
```

2021-07-12 18:57 UTC, ttamttam commented
>     * Malgré leur inexactitude typographique, il me semble que nous préférons utiliser les apostrophes dactylographiques `'` dans le code. J'imagine qu'elles sont plus facilement accessibles sur les claviers. Par contre, on peut tout à fait se pencher sur la question, et pourquoi pas les transformer automatiquement en apostrophes typographiques `’` au niveau du CMS qui se charge d'afficher la documentation, ou alors mettre en place un robot qui fait les modifs pour nous? Je laisse d'autres membres de l'équipe intervenir à ce sujet, on a rien de défini il me semble.

Je ne comprends pas très bien l’argument ? Il y a un certain nombre d’années, je devais faire comme ça : « Ces ann\'ees l\`a, il \'etait un peu p\'enible d’accentuer. ». Mais depuis, ça a quand même évolué dans le bon sens ! Et ça continue (les [deux dispositions de clavier normalisées par l’AFNOR l’année dernière](https://normalisation.afnor.org/actualites/faq-clavier-francais/) permettent de « coder » du français correct beaucoup plus facilement…). Je ne pense pas qu’on préfère utiliser les apostrophe dactylographiques dans le code. Il y a des langages (certainement tous les langage informatiques) qui n’admettent pas autre chose… Et puis il y a plein d’autres langages. Dont les nombreuses variantes de Markdown qui peuvent traiter les deux types d’apostrophes. J’ai plutôt l’impression qu’on n’y fait pas très attention, c’est tout. Comme tu le dis, c’est l’équipe qui doit effectuer ce genre de choix. Et je ne pense pas que cela serait très contraignant à mettre en œuvre, si c’était envisagé.

Lorsque je rédige de la documentation en français, je fais une passe avec [Grammalecte](https://grammalecte.net/) qui vérifie et me propose les corrections pour ce genre de détails et mes nombreuses fautes d’inattention… J’ai juste déroulé sans réfléchir plus que ça à la cohérence avec le reste de la documentation. Donc je vais annuler ces quelques modifications.

>     * Ta PR part d'un mauvais présupposé (on ne pourrait plus définir les autorisations SSH via la ligne de commande). En fait c'est devenu une permission à part entière, et il faut passer par la commande `yunohost user permission add ssh.main <user>`
> 
> 
> Je t'invite à amender ta _pull request_ en remettant les apostrophes droites et en corrigeant plutôt la commande. wink

Ah ! Je ne sais pas comment j’ai fait pour rater ça ? Alors que j’avais bien tenté un `yunohost user --help` !

Cordialement

2021-07-12 21:07 UTC, tituspijean commented
Je suis tout à fait d'accord que cette solution peut faire hurler les puristes, et j'attends avec impatience le développement de la nouvelle norme de clavier. En attendant on va rester dans cet entre-deux. On privilégie le fond à la forme, et on s'évite d'avoir une myriade de formes typographiques parmi nos fichiers. :)

> Ah ! Je ne sais pas comment j’ai fait pour rater ça ? Alors que j’avais bien tenté un yunohost user --help !

Pas de soucis haha, c'est justement le but de la doc de passer ce genre d'info. Merci d'avoir mis le doigt sur le problème déjà.

2021-07-12 21:07 UTC, tituspijean approved these changes

2021-07-13 21:17 UTC, merged