Uptime kuma: Transfer rights to yunohost-apps
YunoHost/doc pull request #1811
Opened 2021-11-02 05:53 UTC by ketsapiwiq

Transfer rights to yunohost-apps

2021-11-04 11:36 UTC, frju365 commented
Does it need to be on the wishlist as it seem to be already packaged ? :) Wishlist is a place for app which haven't been packaged at all for Yunohost. It doesn't seem to be the case for this app.

2021-11-04 18:46 UTC, ketsapiwiq commented
Yes we can totally delete it now, I'll push the revert on my way home

2021-11-04 18:54 UTC, yalh76 requested changes
Can be removed, as it's now packaged for YunoHost ^^

2021-11-04 18:54 UTC, yalh76 commented on pages/02.applications/04.wishlist/apps_wishlist.md
> +| [Uptime Kuma](https://uptime.kuma.pet/) | Self-hosted Uptime Robot | [Upstream](https://github.com/louislam/uptime-kuma) | [Package Draft](https://github.com/YunoHost-Apps/uptime-kuma_ynh) |
```suggestion
```

2021-11-05 15:03 UTC, frju365 approved these changes

2021-11-05 15:04 UTC, merged