Nextcloud and additional stockage
YunoHost/doc pull request #2070
Opened 2022-08-15 11:04 UTC by stilobique

Hello,
I write a quick update about the nextcloud use and about the additional storage use -in French only, look to make the translation this week, maybe later.

2022-08-15 11:31 UTC, ericgaspar requested changes
Fix typos

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +Nextcloud est un service d'hébergement de fichiers, de nombreuses applications peuvent être installées afin de lui offrir de nouvelles fonctionnalités tel qu'un agenda, un répertoire de contacts, des
```suggestion
Nextcloud est un service d'hébergement de fichiers. De nombreuses applications peuvent être installées afin d'offrir à Nextcloud de nouvelles fonctionnalités, telles qu'un agenda, un répertoire de contacts, des notes et plein d'autres possibles (vous pouvez trouver quelques applications dans la partie [applications tiers](#applications-tierces) mais il en existe une multitude suivant vos besoins).
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +Il est relativement simple de monter des dossiers accessibles depuis nextcloud en lecture/écriture et de les
```suggestion
Il est relativement simple de monter des dossiers accessibles depuis Nextcloud en lecture/écriture et de les 
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +Il Vous fait commencer par monter un dossier qui sera disponible pour votre application (je prends jellyfin dans mon
```suggestion
Il vous faut commencer par monter un dossier qui sera disponible pour votre application (je prends Jellyfin dans mon 
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +Certaine application son disponible directement depuis Nextcloud.
```suggestion
# Applications tierces
Certaines applications sont disponibles directement depuis Nextcloud.
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
>  L'application Keeweb sur le catalogue de nextcloud - [apps.nextcloud.com/keeweb](https://apps.nextcloud.com/apps/keeweb)
```suggestion
L'application Keeweb sur le catalogue de Nextcloud - [apps.nextcloud.com/keeweb](https://apps.nextcloud.com/apps/keeweb)
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> + - [Manipulations & Problèmes rencontrés utiles](#manipulations-utiles)
```suggestion
 - [Logiciels clients pour mobile et ordinateur](#logiciels-clients)
 - [Manipulations & problèmes rencontrés utiles](#manipulations-utiles)
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +    - [Partager un dossier entre nextcloud et une application](#partager-un-dossier-entre-nextcloud-et-une-application)
```suggestion
    - [Partager un dossier entre Nextcloud et une application](#partager-un-dossier-entre-nextcloud-et-une-application)
```

2022-08-15 11:31 UTC, ericgaspar commented on pages/04.applications/10.docs/nextcloud/app_nextcloud.fr.md
> +    - [A propos de keeweb](#à-propos-de-keeweb)
```suggestion
 - [Applications tierces](#applications-tierces)
    - [À propos de Keeweb](#à-propos-de-keeweb)
```

2022-08-17 11:14 UTC, ericgaspar approved these changes

2022-08-17 20:46 UTC, merged

2022-08-18 07:50 UTC, stilobique commented
First update about the documentation 🥳 .
Thanks @ericgaspar for your feedback.