Create app_galette
YunoHost/doc pull request #2104
Opened 2022-10-01 15:01 UTC by pp-r

2022-10-01 16:06 UTC, ericgaspar requested changes

2022-10-01 16:06 UTC, ericgaspar commented on pages/04.applications/10.docs/galette/app_galette.md
> +*Galette* Galette is a membership management web application towards non profit organizations. This is before all a free software (as in free speech), community and free (as in beer)! Galette works o
```suggestion
*Galette* is a membership management web application towards non profit organizations. This is before all a free software (as in free speech), community and free (as in beer)! Galette works on any web server that handle PHP.
```

2022-10-01 18:42 UTC, pp-r reviewed
Approve change

2022-10-02 08:25 UTC, ericgaspar approved these changes

2022-10-02 08:25 UTC, merged