Ajout de FAImaison dans les VPS Français.
YunoHost/doc pull request #2126
Opened 2022-10-16 19:47 UTC by ilosu

Ajout de FAImaison dans les VPS Français.

2022-10-17 06:18 UTC, tituspijean requested changes

2022-10-17 06:18 UTC, tituspijean commented on pages/02.administer/10.install/install.fr.md
> +Sélectionnez le matériel sur lequel vous souhaitez installer YunoHost :
A corriger, on dirait un mauvais copier-coller issu du début du fichier.

2022-10-17 07:57 UTC, zamentur commented
Et du coup vous proposer bien des VPS yunohost pré-installés ? Donc les personnes peuvent commencer à l'étape de configuration initiale (voir juste se connecter à la webadmin) ?

2022-10-17 19:45 UTC, ilosu commented on pages/02.administer/10.install/install.fr.md
> +Sélectionnez le matériel sur lequel vous souhaitez installer YunoHost :
J'ai repris via 3 commits (car je débute avec vim & git).

2022-10-18 09:16 UTC, ilosu commented
Oui je vous confirme que dans un premier temps nous allons proposer des yunohost pré-installé où il ne restera que la post-install a réaliser par l'utilisateur.

Dans un second temps nous envisageons même d'automatiser avec une mise à disposition après post-install.

2022-10-18 11:46 UTC, tituspijean approved these changes
Commits to be squashed and merged.

2022-10-18 13:32 UTC, merged