Add autogenerated doc about app resources (manifest v2)
YunoHost/doc pull request #2131
Opened 2022-10-24 19:54 UTC by alexAubin

2022-11-02 20:38 UTC, ericgaspar requested changes
Small typos

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +- to get rid of funky historical, not-super-semantic stuff such as `__FINALPATH__` being replaced by `$final_path` (with underscore), or `__PATH__` being replaced by `$path_url`, etc...
```suggestion
- to get rid of funky historical, not-super-semantic stuff such as `__FINALPATH__` being replaced by `$final_path` (with underscore), or `__PATH__` being replaced by `$path_url`, etc.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +- formalize some aspects such as the existence of the install dir, data dir, apt dependencies, database, etc ... which in turn unlock possible future developments such as computing the space used by
```suggestion
- formalize some aspects such as the existence of the install dir, data dir, apt dependencies, database, etc. which in turn unlock possible future developments such as computing the space used by an app at one given moment, auto-upgrading apt dependencies during Debian major migration, etc.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +   - An `integration` section meant to formalize what minimum yunohost version is required, the list of supported architectures, declare if SSO/LDAP is supported, typical resource usage. This is mean
```suggestion
   - An `integration` section meant to formalize what minimum YunoHost version is required, the list of supported architectures, declare if SSO/LDAP is supported, typical resource usage. This is meant to be displayed both in the catalog (similar to app stores) and on the app info page after installing the app - though this is still work in progress. 
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - They include for example : system user, apt dependencies, install dir, data dir, port, permissions, SQL database ...
```suggestion
    - They include for example: system user, apt dependencies, install dir, data dir, port, permissions, SQL database... 
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +- Permissions are to be initialized using the answer to the `init_main_permission` install question (replacing the `is_public` question). No need to write a boring `if $is_public ...` to add visitors
```suggestion
- Permissions are to be initialized using the answer to the `init_main_permission` install question (replacing the `is_public` question). No need to write a boring `if $is_public...` to add visitors! There is a similar mechanism to init other permissions, e.g. `init_admin_permission` (cf. also the doc about the `permission` resource)
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `ADMIN.md` is expected to be made available somewhere in the info page and should contain technical admin notes. Other pages can be defined (just name it `WHATEVER.md`). Lang codes are also sup
```suggestion
    - `ADMIN.md` is expected to be made available somewhere in the info page and should contain technical admin notes. Other pages can be defined (just name it `WHATEVER.md`). Lang codes are also supported following the existing scheme for the README, eg `README_fr.md` is the French version, hence you can create `ADMIN_fr.md`, etc.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `doc/notifications/post_upgrade.md` : a note to be displayed after the app upgrade. For example in the context of Nextcloud, the fact that you may need to re-enable custom modules manually ?
```suggestion
    - `doc/notifications/post_upgrade.md`: a note to be displayed after the app upgrade. For example in the context of Nextcloud, the fact that you may need to re-enable custom modules manually?
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `doc/notifications/pre_upgrade.d/{version}.md` : a note to be displayed prior to a specific version upgrade.
```suggestion
    - `doc/notifications/pre_upgrade.d/{version}.md`: a note to be displayed prior to a specific version upgrade.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `doc/notifications/pre_upgrade.md` : a note to be displayed prior to any upgrade of this app.
```suggestion
    - `doc/notifications/pre_upgrade.md`: a note to be displayed prior to any upgrade of this app.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `doc/notifications/post_install.md` : a note to be displayed after the app install. Typically to explain post-install operations to be performed manually by the admin and that cannot be automat
```suggestion
    - `doc/notifications/post_install.md`: a note to be displayed after the app install. Typically to explain post-install operations to be performed manually by the admin and that cannot be automated.
```

2022-11-02 20:38 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/14.advanced/03.packaging_v2/packaging_v2.md
> +    - `doc/notifications/pre_install.md` : a note to be displayed prior to the app install. Typically to warn of something unusual, such as "the app install will automatically add 1GB swap to the sys
```suggestion
    - `doc/notifications/pre_install.md`: a note to be displayed prior to the app install. Typically to warn of something unusual, such as "the app install will automatically add 1GB swap to the system".
```

2023-01-29 20:39 UTC, alexAubin commented
Superseded by https://github.com/YunoHost/doc/pull/2162

2023-01-29 20:39 UTC, closed without merging