Update email_configure_relay.fr.md
YunoHost/doc pull request #2221
Opened 2023-02-20 15:11 UTC by stilobique

Write a quick documentation about the relay SMTP setup with the web administration setup, make a tab config to split cli and webadmin space.

2023-02-20 15:37 UTC, ericgaspar requested changes

2023-02-20 15:37 UTC, ericgaspar commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +- **Adresse du relais SMTP** : L'url pour le serveur SMTP.
```suggestion
- **Adresse du relais SMTP** : L'URL pour le serveur SMTP.
```

2023-04-29 10:29 UTC, stilobique commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +- **Adresse du relais SMTP** : L'url pour le serveur SMTP.
Fixed :)

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +choisis et configurés.
```suggestion
Une fois correctement installé, le fonctionnement est transparent pour l’utilisateur. Vos correspondants verront vos e-mails comme s’ils venaient de votre propre serveur, mais ils auront été transmis par le relais SMTP que vous aurez choisi et configuré.
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +Il est possible de configurer via l'admin web ou en *command line*.
```suggestion
Il est possible de configurer soit via la webadmin, soit en ligne de commande
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +[/ui-tab] [ui-tab title="Configuration en Web Admin"]
(Idéalement ce serait cool que la webadmin soit proposée en premier plutôt que la CLI, la CLI devrait être pour les utilisateurs avancés donc mise au second plan)

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.md
> +You can configure with your webadmin or in *cli*.
```suggestion
It can be configured either from the webadmin or the command line.
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.md
> +[ui-tabs position="top-left" active="0" theme="lite"] [ui-tab title="Config en CLI"]
```suggestion
[ui-tabs position="top-left" active="0" theme="lite"] [ui-tab title="From the command line"]
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +[ui-tabs position="top-left" active="0" theme="lite"] [ui-tab title="Configuration en CLI"]
```suggestion
[ui-tabs position="top-left" active="0" theme="lite"] [ui-tab title="En ligne de commande"]
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +[/ui-tab] [ui-tab title="Configuration en Web Admin"]
```suggestion
[/ui-tab] [ui-tab title="Depuis la webadmin"]
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.md
> +[/ui-tab] [ui-tab title="Config on Web Admin"]
```suggestion
[/ui-tab] [ui-tab title="From the webadmin"]
```

2023-06-20 16:43 UTC, alexAubin commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.md
> +- **SMTP relay password** : Your server access password.
```suggestion
- **SMTP relay password** : Your SMTP relay password.
```

2023-06-21 11:46 UTC, stilobique commented on pages/02.administer/45.tutorials/35.email_relay/email_configure_relay.fr.md
> +[/ui-tab] [ui-tab title="Configuration en Web Admin"]
Je ne sais pas trop comment s'organiser, mais écrire des règles de principes quelque part serait pas mal. À moins qu'il y ait déjà quelques chose sur le forum ou ailleurs ?

2023-06-22 23:01 UTC, merged