Create sso_ldap_integration.fr.md
YunoHost/doc pull request #2450
Opened 2024-04-17 18:24 UTC by misossdotnet

write french doc

2024-04-17 21:41 UTC, misossdotnet reviewed
Possible adding KB : https://forum.yunohost.org/t/solved-use-yunohost-as-a-ldap-server-connect-other-machines-to-it/2865/11

Open LDAP on Local Network : edit `/etc/default/slapd` and **ADD** in  `SLAPD_SERVICES` : `ldap://{YOUR_LOCAL_IP}:389/` and restart service

2024-09-27 07:02 UTC, ericgaspar requested changes

2024-09-27 07:02 UTC, ericgaspar commented on pages/06.contribute/10.packaging_apps/60.advanced/30.sso_ldap_integration/sso_ldap_integration.fr.md
> +Le cas échéant, vous pouvez créer des autorisations « secondaires » pour votre application, par exemple pour autoriser uniquement un groupe spécifique de personnes à accéder à l'interface utilisateur
```suggestion
Le cas échéant, vous pouvez créer des autorisations « secondaires » pour votre application, par exemple pour autoriser uniquement un groupe spécifique de personnes à accéder à l'interface utilisateur d'administration de l'application. Par exemple :
```

2024-09-27 07:02 UTC, ericgaspar approved these changes

2024-09-27 07:02 UTC, merged